# Generated by Django 5.2 on 2025-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='The user this phone user belongs to')),
                ('pps_id', models.IntegerField(help_text='The PPS ID of the user')),
            ],
        ),
    ]
