services:
  mock:
    build: 
      context: ./backend/mock
      dockerfile: ./docker/Dockerfile
    command: ["/bin/bash", "/app/entrypoint.sh"]
    volumes:
      - ./backend/mock:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=changeme
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,mock
      - KEYS_DIR=/keys
      - POSTGRES_DB=db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_RUNTIME_USER=django
      - POSTGRES_RUNTIME_PASSWORD=django
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_RUNTIME_USER: django
      POSTGRES_RUNTIME_PASSWORD: django
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "user", "-d", "my_project_db"]
        interval: 10s
        retries: 5
        start_period: 5s
        timeout: 5s
  
  router:
    image: ghcr.io/apollographql/router:v2.1.1
    ports:
      - "4000:4000"
    volumes:
      - ./router/router.yaml:/dist/config/router.yaml
      - ./router/supergraph.graphql:/dist/schema/supergraph.graphql
    command:
      - -c
      - /dist/config/router.yaml
      - -s
      - /dist/schema/supergraph.graphql

  rover:
    build:
      context: ./rover/docker
      dockerfile: Dockerfile
    volumes:
      - ./rover/output:/output
      - ./rover/config/:/config/
                
networks:
  backend:
    driver: bridge

volumes:
  db_data:
            