# Generated by Django 5.2 on 2025-04-10 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the call queue', max_length=100)),
                ('members', models.ManyToManyField(blank=True, help_text='Users that are members of this call queue', related_name='call_queues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Call start time')),
                ('end_time', models.DateTimeField(help_text='Call end time')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Call duration in seconds')),
                ('caller_id', models.CharField(help_text='Identifier for the caller (could be a phone number or reference ID)', max_length=50)),
                ('callee_id', models.CharField(help_text='Identifier for the callee (could be a phone number or reference ID)', max_length=50)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], help_text='Direction of the call', max_length=10)),
                ('user', models.ForeignKey(help_text='The user this call belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to=settings.AUTH_USER_MODEL)),
                ('call_queue', models.ForeignKey(blank=True, help_text='Call queue associated with the call, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='phone.callqueue')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='First name', max_length=100)),
                ('prefixlastname', models.CharField(blank=True, help_text='Prefix of the last name (if any)', max_length=100, null=True)),
                ('lastname', models.CharField(help_text='Last name', max_length=100)),
                ('mobile_nr', models.CharField(blank=True, help_text='Mobile phone number', max_length=20, null=True)),
                ('landline_nr', models.CharField(blank=True, help_text='Landline number or extension', max_length=20, null=True)),
                ('department', models.CharField(blank=True, help_text='Department name (if applicable)', max_length=100, null=True)),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('personal', 'Personal')], help_text='Contact type: internal, external, or personal', max_length=10)),
                ('user', models.ForeignKey(blank=True, help_text='Link to a User for internal contacts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
