supergraph:
  # The socket address and port to listen on
  listen: 0.0.0.0:4001
  # Introspection should never run on PROD
  introspection: true

sandbox:
  # Should be disabled in PROD
  enabled: true

homepage:
  enabled: false

cors:
  allow_any_origin: true

headers:
  all:
    request:
      - propagate:
          named: "X-User-ID"
          default: "2"
      - remove:
          named: "X-Rover-Introspection"